# Generated by Django 2.2 on 2023-03-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='municipality',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Municipality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm_base.Owner', verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='state',
            field=models.CharField(default='unknown', max_length=255, verbose_name='State'),
            preserve_default=False,
        ),
    ]
